-- Generated from generator/demo_specs/aws-malaysia-semiconductor-capacity.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-semiconductor-capacity
-- This is the schema that is actually deployed for MY_SEMICONDUCTOR_CAPACITY.

-- Alerts fire on the bottom tail of Fab Utilization
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_FAB_UTILIZATION) AS T
  FROM RAW.PRODUCTION_SCHEDULE
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_FAB_UTILIZATION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_FAB_UTILIZATION), 2) AS AVG_FAB_UTILIZATION,
  ROUND(AVG(f.KPI_CYCLE_TIME_AVG), 2) AS AVG_CYCLE_TIME,
  ROUND(AVG(f.KPI_QUEUE_TIME), 2) AS AVG_QUEUE_TIME,
  ROUND(AVG(f.KPI_HOT_LOTS), 2) AS AVG_HOT_LOTS
FROM RAW.PRODUCTION_SCHEDULE f
JOIN RAW.FAB_CAPACITY e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_FAB_UTILIZATION), 2) AS AVG_FAB_UTILIZATION,
  ROUND(AVG(f.KPI_CYCLE_TIME_AVG), 2) AS AVG_CYCLE_TIME,
  ROUND(AVG(f.KPI_QUEUE_TIME), 2) AS AVG_QUEUE_TIME,
  ROUND(AVG(f.KPI_HOT_LOTS), 2) AS AVG_HOT_LOTS
FROM RAW.PRODUCTION_SCHEDULE f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_FAB_UTILIZATION) AS KPI_FAB_UTILIZATION, AVG(KPI_CYCLE_TIME_AVG) AS KPI_CYCLE_TIME_AVG, AVG(KPI_QUEUE_TIME) AS KPI_QUEUE_TIME, AVG(KPI_HOT_LOTS) AS KPI_HOT_LOTS FROM RAW.PRODUCTION_SCHEDULE),
     en AS (SELECT SUM(KPI_WIP_WAFERS) AS KPI_WIP_WAFERS, SUM(KPI_OUTPUT_MTD) AS KPI_OUTPUT_MTD FROM RAW.FAB_CAPACITY)
  SELECT 1 AS SORT_ORDER, 'Fab Utilization' AS TITLE, KPI_FAB_UTILIZATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FAB_UTILIZATION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'WIP (Wafers)' AS TITLE, KPI_WIP_WAFERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_WIP_WAFERS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Cycle Time (Avg)' AS TITLE, KPI_CYCLE_TIME_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CYCLE_TIME_AVG)) AS DECIMAL(38,0))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Output (MTD)' AS TITLE, KPI_OUTPUT_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_OUTPUT_MTD) / 1000)) AS DECIMAL(38,0))) || 'K' || ' ' || 'wafers' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Queue Time' AS TITLE, KPI_QUEUE_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_QUEUE_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'hrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Hot Lots' AS TITLE, KPI_HOT_LOTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_HOT_LOTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
