-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Production Capacity Planning
-- ============================================================================
USE DATABASE SEMICONDUCTOR_CAPACITY;
USE SCHEMA ML;

-- ML.FORECAST: CAPACITY_DEMAND_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CAPACITY_DEMAND_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.UTILIZATION_TIMESERIES'),
  SERIES_COLNAME => 'FAB_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.CAPACITY_DEMAND_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.CAPACITY_DEMAND_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.TOP_INSIGHTS: BOTTLENECK_DRIVERS_MODEL
-- Call: SELECT * FROM TABLE(ML.BOTTLENECK_DRIVERS_MODEL!GET_INSIGHTS(INPUT_DATA => ...));

