-- ============================================================================
-- 99_RESET.SQL — Reset Production Capacity Planning to clean demo state
-- ============================================================================
USE DATABASE SEMICONDUCTOR_CAPACITY;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.DEMAND_VS_CAPACITY REFRESH;
ALTER DYNAMIC TABLE CURATED.UTILIZATION_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.BOTTLENECK_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE CURATED.REVENUE_AT_RISK REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SEMICONDUCTOR_CAPACITY.RAW.FAB_CAPACITY → 12
-- SELECT COUNT(*) FROM SEMICONDUCTOR_CAPACITY.RAW.DEMAND_FORECASTS → 1000
-- SELECT COUNT(*) FROM SEMICONDUCTOR_CAPACITY.RAW.PRODUCTION_SCHEDULE → 8000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS RESUME;
